### ISSUE TITLE
Remove pandas version restriction

### ISSUE THREAD

**Issue by theavey** [goldmansachs/gs-quant#157]
**Describe the problem.**
There are bug fixes and features available in newer versions of pandas that I would like to have access to.
In my non-thorough testing, this package works just fine with newer versions of pandas (1.2.0).

**Describe the solution you'd like**
Testing of the package with the version constraint removed followed by removing the version restriction.

**Describe alternatives you've considered**
I currently just have multiple environments with different package versions to work around this restriction.
If there are issues found, the restriction is reasonable to remain, but I would be willing to help fix issues that are found.

**Are you willing to contribute**
Yes

**Additional context**
Because pandas follows semantic versioning, there should be no breaking changes going from 1.0 to 1.2 unless you are relying on some internal implementation details in pandas or a bug.

**Comment by Cruppelt** [comment]
Thanks for reaching out theavey! This is great advice and we are looking into this internally.

**Comment by theavey** [comment]
https://iscinumpy.dev/post/bound-version-constraints/

On a related note, we had some issues internally when #211 was merged, which included a quite restrictive matplotlib version specification

**Comment by AnastasiyaB** [comment]
Thanks Tom, will look into that one too.

**Comment by theavey** [comment]
This seems fixed by #221 

https://github.com/goldmansachs/gs-quant/pull/221/commits/db0156e74aef93c32a3b94b936386e7ac254ed2a#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R71
